### ISSUE TITLE
[Minor] Backpack's contents partially visible if the character sheet is not big enough

### ISSUE THREAD

**Issue by SIRIUS05627** [greedyj4ck/DEGENESIS-FoundryVTT#61]
Mostly QoL thing for long campaigns with a lot of items in each character sheet
Okay
![image](https://user-images.githubusercontent.com/48809718/183907227-18134a30-fb22-4352-9c32-edd14df63d65.png)
Not so good
![image](https://user-images.githubusercontent.com/48809718/183907252-c8aa453b-607a-4958-ac71-f1110d997327.png)

**Comment by samueljurado12** [comment]
Hi @SIRIUS05627 , as a workaround meanwhile this is fixed you can create a custom item with type transportation and encumbrance 0 and add it to the characters. The problem seems to be just with the last line, so once you add this dummy item you can see the full backpack content. 

It's not the proper solution, but better than nothing!

**Comment by greedyj4ck** [comment]
> 

Tried to re-created the bug on my side but everything (except a glitch creating two item summary divs when you drag n drop item on a backpack thats minimized). Are you using default Foundry client or a specific web browser? 

@samueljurado12  can you provide info about your web browser also ?

**Comment by samueljurado12** [comment]
I'm using Chrome. Sharing also my foundry and system version. I know it's not the latest, but can't update yet due to some of our systems not being adapted to v10 of foundry. My players also use chrome as far as I know and they have the same problem.
![image](https://user-images.githubusercontent.com/26406032/204658510-ca5aad36-60f1-42b9-add8-9cd07cf3eb48.png)

**Comment by greedyj4ck** [comment]
Thanks for feedback @samueljurado12 . I discovered another equipment and containers related issue thanks to you.  This issue also should be fixed in fb61aa7a61cdd3b6acfeb16fb872a57e272d67cb and upcoming patch, so I'm closing it for now :) 

Also you can run another instance of Foundry with different Foundry Data Folder :) If you need more help, hop on our discord :) https://discord.gg/gDc9pkwcFE
