### ISSUE TITLE
links in history tab - names in the chat.

### ISSUE THREAD

**Issue by Vincekettu** [greedyj4ck/DEGENESIS-FoundryVTT#64]
We can't link things like journals or scenes or npcs in the History/Biography section on the character sheet

![image](https://user-images.githubusercontent.com/75499666/192731562-2d6bc351-69f2-4caf-966b-ba35eaee4d91.png)

Also in the chat, the dialogs are correct but the all the rolls indicate the owner of the token instead of the token name 
As a GM, any NPC roll is called Gamemaster.
![image](https://user-images.githubusercontent.com/75499666/192732221-90d13933-39b0-44a6-8b1f-14bdc391445b.png)
(same token)

**Comment by greedyj4ck** [comment]
Rolls will display proper actor's name in chat message. 

![Image](https://user-images.githubusercontent.com/33233389/193478815-595ac77a-24c3-4819-9aa3-043a7e717399.png)

Links in text editor fields are now properly 'enchanced'.  Need to check other text editor fields, and apply the fix. Will be fixed in 0.5.1

![Image](https://user-images.githubusercontent.com/33233389/193478859-462a5f32-1942-4504-ac80-44bb2119b73b.png)

**Comment by greedyj4ck** [comment]
Fixed. Closing the issue :)

**Comment by Vincekettu** [comment]
oh thanks a lot !!!
