### ISSUE TITLE
Armor Description

### ISSUE THREAD

**Issue by Durak-Git** [greedyj4ck/DEGENESIS-FoundryVTT#74]
![image](https://user-images.githubusercontent.com/97435195/197880904-79d9d683-dc6b-4450-88b2-a7902162e04a.png)
Lack informations for armor , gives an object Object
No errors for shield, but 2-3 have an empty description (perhaps it's normal)

**Comment by greedyj4ck** [comment]
Other items are fine?

**Comment by greedyj4ck** [comment]
There is issue with line 23 in armor item template.

 {{editor enrichment.system.description engine="prosemirror" target="system.description" button=true owner=owner editable=editable}}

There should be enrichment.system.description.value - that's why entire object is passed instead just html stuff. Gonna fix it in nearest release.

**Comment by Durak-Git** [comment]
Not checked every other item (only armors and shields), but I think "no"
I will check tomorrow

**Comment by Durak-Git** [comment]
Only in armor, I saw no issues elsewhere

**Comment by greedyj4ck** [comment]
Fixed :)
